# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [nogo, battle]
patreon: # Replace with a single Patreon username justin3687
open_collective: # Replace with a single Open Collective username voodoo.io
ko_fi: # Replace with a single Ko-fi username java
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/Babel runtime
community_bridge: # Replace with a single Community Bridge project-name e.g., slack-foundry
liberapay: # Replace with a single Liberapay username Airassult
issuehunt: # Replace with a single IssueHunt username foxtrot
otechie: # Replace with a single Otechie username HANNA
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['Https://marchofthedimes.org',"https://discord.com", 'https://dollarshaveclub.com']
